spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "Your url"
    username: "Your username"
    password: "Your password"
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username: "Your Email"
    password: "YourEmail smtp Password"
    default-encoding: utf-8
    properties:
      mail:
        debug: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_
server:
  port: 80
